module.exports = {
	ask_name:"Hi, I am a Learning Counsellor. Please tell me your name",
	name_exists : "Sorry, the username already exists. Please choose another name",
	initial_greet : "I am a Learning Counsellor. How are you doing today ?",
	initial_greet_copy:" How are you doing today ?",
	user_ok : "That's good to hear",
	user_first_time : "This seems to be your first chat with me. So,I would like to know you little better before we proceed. Is that ok? (Yes/No)",
	user_existing : "I can help you with suggestion on learning paths for your aspirational skills. What new skill do you intend to acquire?",
	user_not_ok : "Sorry to hear that.",
	bot_help : "I hope I can help you with your query.",
	kb_skill_exists : "Great, let me figure out how you can get there. Give me a minute.",
	kb_skill_not_exists:"I don’t have a ready answer for that. I will find out and inform you about this. Sorry about that",
	current_skills :"Please tell me the technical skills you have currently. Just a list of the skills will do for now",
	thank_you :"Thank you ",
	acquire_skills : "for that information. What new skill do you intend to acquire?",
	recommend_skills : "Here is the best possible learning path as per my records. Please reach out to the academy to get the schedule of the trainings for these skills.",
	happy_exit : "Glad I could be of help. Thank you for your patience. Have a good day. Bye",
	unhappy_exit:"I am sorry that the recommendation was not suitable. I would suggest you speak to your point of contact from academy for more options.",
	default_response:"I am sorry, I didn't get you , please say again",
	user_direct:" for that information. What new skill do you intend to acquire?",
	no_topic_exit:" Thank you for your patience. Have a good day.  Bye !!",
	ask_more:"Thank You!! Do you have any other queries , I can help with ?",
	ask_more_not_help:"Sorry aboout that. Do you have any other queries , I can help with ?",
	exit_confirm:"Do you want to exit from the chat ? (Yes/No)",
	normal_exit:" Thank You , Bye",
	digi_dl:"For any other queries, send a mail to ",
	digi_yammer:"To interact with your peers on the program, visit here [DU Yammer]",
	digi_cmooc:"Do you want to know more learnings related to digital? Visit [CMOOC]"
};
